// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSQ34FkW6LHTUAm3GMgSWdK8AL-HwTkx0',
    appId: '1:535343347974:web:02bd4457934588a9254687',
    messagingSenderId: '535343347974',
    projectId: 'homex-fd825',
    authDomain: 'homex-fd825.firebaseapp.com',
    storageBucket: 'homex-fd825.appspot.com',
    measurementId: 'G-1MZXH5318K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjLyqpF-Z-S59aPKfbRg7EVGdeNS3TGU',
    appId: '1:535343347974:android:fa6b269cdf771746254687',
    messagingSenderId: '535343347974',
    projectId: 'homex-fd825',
    storageBucket: 'homex-fd825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuwQagDY05ffm5Cq2SC2qc4MCsWB-ld8Y',
    appId: '1:535343347974:ios:a66e19ff1f69c099254687',
    messagingSenderId: '535343347974',
    projectId: 'homex-fd825',
    storageBucket: 'homex-fd825.appspot.com',
    iosBundleId: 'com.example.homex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuwQagDY05ffm5Cq2SC2qc4MCsWB-ld8Y',
    appId: '1:535343347974:ios:61ff7d5f0a90fa14254687',
    messagingSenderId: '535343347974',
    projectId: 'homex-fd825',
    storageBucket: 'homex-fd825.appspot.com',
    iosBundleId: 'com.example.homex.RunnerTests',
  );
}
